### ISSUE TITLE
Practica DLL

### ISSUE THREAD

**Issue by javiern-778** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-javiern-778#2]
[DLL.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-javiern-778/files/6353271/DLL.pdf)

**Comment by Ferch0419** [comment]
Porcentaje obtenido: 20% Calificado por Fernando Miguel López.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
